"""
Frozen data contract for the protocol sufficiency task.

DO NOT EDIT THIS FILE. Your code imports these types; the scoring harness
imports the same types. If you think something here is wrong, say so in your
write-up rather than changing it.

Python 3.11+, pydantic v2.
"""

from __future__ import annotations

import hashlib
import re
import unicodedata
from decimal import Decimal
from typing import Literal, Optional, Protocol

from pydantic import BaseModel, Field, model_validator

CONTRACT_VERSION = "0.2"

# Changelog
# 0.2  Added GAP_RANGE_NOT_POINT and GAP_DEFERRED_TO_DISPLAY to GapCode.
#      Added has_wet_lab StudyFeature.
#      Added FieldSpec.applies_when_any (OR semantics alongside AND).
#      Added verdict/code consistency validation on Finding.
#      Adding gap codes is a MINOR event: codes are values, not schema, so
#      existing finding_id hashes are unaffected.


# ---------------------------------------------------------------------------
# Canonicalization. All spans index into canonical text, never raw text.
# ---------------------------------------------------------------------------

def canonicalize(raw: str) -> tuple[str, str]:
    """Normalize document text. Returns (canonical_text, sha256_hex).

    Deterministic and stable. Deliberately does NOT case-fold, strip
    punctuation, or normalize units -- case is signal for entity mentions and
    unit handling belongs in the validator where it can be typed.
    """
    t = unicodedata.normalize("NFC", raw)
    t = t.replace("\r\n", "\n").replace("\r", "\n")
    t = re.sub(r"[ \t\u00a0]+", " ", t)
    t = re.sub(r" *\n", "\n", t)
    t = re.sub(r"\n{3,}", "\n\n", t)
    t = t.strip()
    return t, hashlib.sha256(t.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# Spans
# ---------------------------------------------------------------------------

class Span(BaseModel):
    start: int = Field(..., ge=0)   # inclusive, offset into canonical text
    end: int = Field(..., ge=0)     # exclusive
    text_sha: str

    @model_validator(mode="after")
    def _check(self):
        if self.end <= self.start:
            raise ValueError("zero-width or inverted span")
        return self

    def slice(self, canonical_text: str) -> str:
        return canonical_text[self.start:self.end]


# ---------------------------------------------------------------------------
# Study profile -- gates which fields apply
# ---------------------------------------------------------------------------

StudyFeature = Literal[
    # has_wet_lab gates fields that apply to any bench work regardless of assay
    # (centrifugation, reagent identity, assay protocols). Without it, purely
    # computational papers accumulate false gaps on every wet-lab field.
    "has_wet_lab",
    "has_animals",
    "has_cell_lines",
    "has_qpcr",
    "has_flow_cytometry",
    "has_western_blot",
    "has_ihc",
    "has_xenograft",
    "has_drug_treatment",
]


class StudyProfile(BaseModel):
    """Which experiment types this paper contains. Drives applicability."""
    features: dict[StudyFeature, bool]
    evidence: dict[StudyFeature, Span] = {}

    def has(self, feature: str) -> bool:
        return bool(self.features.get(feature, False))  # type: ignore[arg-type]


# ---------------------------------------------------------------------------
# Field pack (loaded from YAML, see fields/)
# ---------------------------------------------------------------------------

Verdict = Literal[
    "FIELD_OK",           # present and usable
    "FIELD_ABSENT",       # not stated anywhere
    "FIELD_UNRESOLVED",   # stated but not usable (vague, unparseable, deferred)
    "FIELD_NA",           # applicability predicate false
]

GapCode = Literal[
    "GAP_ABSENT",               # field required and missing
    "GAP_VAGUE",                # qualitative where a quantity is needed
    "GAP_UNPARSEABLE",          # present, failed to parse as the declared type
    "GAP_DIMENSION_MISMATCH",   # parsed but wrong physical dimension
    "GAP_OUT_OF_RANGE",         # parsed, right dimension, implausible value
    "GAP_RANGE_NOT_POINT",      # a range where a point value is required
    "GAP_DEFERRED_TO_REF",      # "as previously described (ref N)"
    "GAP_DEFERRED_TO_DISPLAY",  # "the indicated times", "see Fig 3"
]

# GAP_RANGE_NOT_POINT was previously only expressible as a SlotVerdict, so a
# range gap could be detected but not emitted.
#
# GAP_DEFERRED_TO_DISPLAY is separated from GAP_DEFERRED_TO_REF because the two
# behave differently under triage. A deferral to a figure is often recoverable
# (the axis carries the value); a deferral to another paper usually is not, and
# frequently chains into a further deferral. Collapsing them hides that split.

# Which gap codes are legal for which verdict. Enforced on Finding.
_VERDICT_CODES: dict[str, set[str]] = {
    "FIELD_ABSENT": {"GAP_ABSENT"},
    "FIELD_UNRESOLVED": {
        "GAP_VAGUE",
        "GAP_UNPARSEABLE",
        "GAP_DIMENSION_MISMATCH",
        "GAP_OUT_OF_RANGE",
        "GAP_RANGE_NOT_POINT",
        "GAP_DEFERRED_TO_REF",
        "GAP_DEFERRED_TO_DISPLAY",
    },
    "FIELD_OK": set(),   # no gap; a Finding should not exist
    "FIELD_NA": set(),   # predicate false; a Finding should not exist
}

FieldType = Literal["quantity", "enum", "identifier", "sequence", "boolean", "text"]


class FieldSpec(BaseModel):
    field_id: str
    type: FieldType
    dimension: Optional[str] = None          # for quantity fields
    canonical_unit: Optional[str] = None
    plausible_range: Optional[tuple[Decimal, Decimal]] = None
    enum_values: Optional[list[str]] = None
    applies_when: list[StudyFeature] = []      # ALL must hold; empty = always
    applies_when_any: list[StudyFeature] = []  # at least ONE must hold; empty = ignored
    # Both are ANDed together. antibody.identifier needs
    #   applies_when=[has_wet_lab], applies_when_any=[has_western_blot, has_ihc,
    #   has_flow_cytometry]
    # which AND-only semantics could not express.
    provenance: list[dict[str, str]] = []    # guideline + item number
    sensitivity: Literal["HIGH", "MED", "LOW"] = "HIGH"
    sensitivity_source: Literal["expert", "default"] = "default"
    description: str = ""


class FieldPack(BaseModel):
    version: str
    fields: list[FieldSpec]

    def by_id(self, field_id: str) -> Optional[FieldSpec]:
        return next((f for f in self.fields if f.field_id == field_id), None)

    def applicable(self, profile: StudyProfile) -> list[FieldSpec]:
        def applies(f: FieldSpec) -> bool:
            if not all(profile.has(x) for x in f.applies_when):
                return False
            if f.applies_when_any and not any(
                profile.has(x) for x in f.applies_when_any
            ):
                return False
            return True

        return [f for f in self.fields if applies(f)]


# ---------------------------------------------------------------------------
# Extraction proposals -- what a model (or regex, or gazetteer) suggests
# ---------------------------------------------------------------------------

class FieldObservation(BaseModel):
    """A proposal. Never trusted as a value; it goes to a validator."""
    field_id: str
    raw_text: str
    span: Span
    detector: str          # which detector produced this, for your own analysis


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

class Finding(BaseModel):
    finding_id: str
    field_id: str
    code: GapCode
    span: Span
    verdict: Verdict
    raw_text: Optional[str] = None
    canonical_value: Optional[str] = None
    canonical_unit: Optional[str] = None
    sensitivity: Literal["HIGH", "MED", "LOW"]
    detail: dict = {}

    @model_validator(mode="after")
    def _verdict_matches_code(self):
        legal = _VERDICT_CODES[self.verdict]
        if not legal:
            raise ValueError(
                f"verdict {self.verdict} carries no gap; do not emit a Finding"
            )
        if self.code not in legal:
            raise ValueError(
                f"code {self.code} is not legal for verdict {self.verdict}; "
                f"legal codes are {sorted(legal)}"
            )
        return self


def finding_id(doc_id: str, field_id: str, code: str, span: Span) -> str:
    """Deterministic identity. Must not depend on model, prompt, or run time."""
    payload = "\u001f".join(
        [doc_id, span.text_sha, str(span.start), str(span.end), field_id, code]
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:32]


class Report(BaseModel):
    doc_id: str
    text_sha: str
    contract_version: str = CONTRACT_VERSION
    field_pack_version: str
    profile: StudyProfile
    findings: list[Finding]


# ---------------------------------------------------------------------------
# Model client -- INJECTED, never constructed inside your modules
# ---------------------------------------------------------------------------

class ModelClient(Protocol):
    def complete(self, prompt: str, *, max_tokens: int = 1024) -> str:
        """Return raw completion text. Implementations may cache by prompt hash."""
        ...


# ---------------------------------------------------------------------------
# The one function you must implement
# ---------------------------------------------------------------------------

def analyze(
    raw_text: str,
    doc_id: str,
    pack: FieldPack,
    model: Optional[ModelClient] = None,
) -> Report:
    """Entry point. The harness calls exactly this.

    Must be a pure function: no writes to disk or network beyond the injected
    model client, no global state, and identical output on repeat calls given
    the same model responses.
    """
    raise NotImplementedError
